# Generated by Django 3.0.5 on 2020-05-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200531_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='last_name',
        ),
    ]
