# Generated by Django 3.0.5 on 2020-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productmodel_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='contenido',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='descripcion_corta',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='preview_image',
            field=models.ImageField(default=1, upload_to='product_images/preview_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/slider_images'),
        ),
    ]
