# Generated by Django 2.1.15 on 2020-06-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200602_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
