# Generated by Django 2.1.15 on 2020-06-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='slug',
        ),
    ]
